export { default as MetaData } from "./MetaData";
export { default as Error } from "./Error/Error";
export { default as Navbar } from "./Navbar/Navbar";
export { default as Footer } from "./Footer/Footer";
export { default as Home } from "./Home/Home";
export { default as About } from "./About/About";
export { default as Contact } from "./Contact/Contact";
export { default as Skills } from "./Skills/Skills";
export { default as Portfolio } from "./Portfolio/Portfolio";
export { default as Container } from "./Containers/Container";
export { default as BlogPost } from "./Blogs/BlogPost";
// export { default as MyLoader } from "./Containers/Loader/MyLoader";
